hl.on("hyprland.start", function()
    hl.exec_cmd("noctalia")
    hl.exec_cmd("kdeconnectd")
    hl.exec_cmd("gsr-ui launch-hide-announce")
    hl.exec_cmd("noctalia msg notification-dnd-toggle")
end)
