-- Generated by nwg-displays on 2026-08-20 at 11:53:13. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@165.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "sunshine",
    mode = "3840x2160@60.0",
    position = "1920x0",
    scale = 2.0
})
