-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "macos-tahoe-cursor")
hl.env("XCURSOR_THEME", "macos-tahoe-cursor")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_SIZE", "24")

hl.config({
	cursor = {
		inactive_timeout = 10,
	},
})
